version: '3.8'

networks:
  prometheus-net:
    name: ${PROMETHEUS_NETWORK:-prometheus-net}
    driver: overlay
    attachable: true

volumes:
  prometheus_data:
  swarmetheus_data:

services:
  swarmetheus:
    image: rjchicago/swarmetheus:${VERSION:-latest}
    build:
      context: swarmetheus
    networks:
      - prometheus-net
    environment:
      ENV: "${ENV:-dev}"
      HOSTNAME: "{{.Node.Hostname}}" # <-- Standard Swarm Mode
      PROMETHEUS_NETWORK: ${PROMETHEUS_NETWORK:-prometheus-net}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - swarmetheus_data:/swarmetheus_data
      - ./swarmetheus/scripts:/swarmetheus/scripts
      - ./swarmetheus/rules:/swarmetheus/rules
      - ./swarmetheus/env:/swarmetheus/env
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus
    user: root
    command:
      - "--config.file=/swarmetheus_data/config/prometheus.yml"
      - "--storage.tsdb.path=/prometheus_data"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-lifecycle"
      - "--web.external-url=http://localhost:9090"
    networks:
      - prometheus-net
    volumes:
      - prometheus_data:/prometheus_data
      - swarmetheus_data:/swarmetheus_data
    ports:
      - "9090:9090"

