version: '3.8'

networks:
  prometheus-net:
    external: true
    name: ${PROMETHEUS_NETWORK:-prometheus-net}

volumes:
  prometheus_data:
  swarmetheus_files:

services:
  swarmetheus:
    image: rjchicago/swarmetheus:${VERSION:-latest}
    build:
      context: swarmetheus
    networks:
      - prometheus-net
    environment:
      ENV: "${ENV:-dev}"
      HOSTNAME: "{{.Node.Hostname}}" # <-- Standard Swarm Mode
      PROMETHEUS_NETWORK: ${PROMETHEUS_NETWORK:-prometheus-net}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - swarmetheus_files:/swarmetheus/files
      - ./swarmetheus/scripts:/swarmetheus/scripts
      - ./swarmetheus/env:/swarmetheus/env
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus
    networks:
      - prometheus-net
    volumes:
      - prometheus_data:/prometheus_data
      - swarmetheus_files:/etc/prometheus/files/swarmetheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

