global:
  scrape_interval: 30s
  scrape_timeout: 30s
  evaluation_interval: 30s

rule_files:
  - rules/*.yml
  - rules/swarmetheus/*.yml

scrape_configs:
  - job_name: 'swarmetheus'
    file_sd_configs:
    - files:
      - files/swarmetheus/*.yml

# - job_name: 'node-exporter'
#   file_sd_configs:
#   - files:
#     - files/swarmetheus/node-exporter.yml
#   relabel_configs:
#     - source_labels: [instance]
#       target_label: __tmp_instance
#       regex: '(.+)'
#       replacement: '${1};'
#     - source_labels: [__tmp_instance, __address__]
#       separator: ''
#       target_label: instance
#       regex: '([^:;]+)((:[0-9]+)?|;(.*))'
#       replacement: '${1}'

# - job_name: 'cadvisor'
#   file_sd_configs:
#   - files:
#     - files/swarmetheus/cadvisor.yml
#   relabel_configs:
#     - source_labels: [instance]
#       target_label: __tmp_instance
#       regex: '(.+)'
#       replacement: '${1};'
#     - source_labels: [__tmp_instance, __address__]
#       separator: ''
#       target_label: instance
#       regex: '([^:;]+)((:[0-9]+)?|;(.*))'
#       replacement: '${1}'

  # # https://prometheus.io/docs/guides/dockerswarm/
  # # Make Prometheus scrape itself for metrics.
  # - job_name: 'prometheus'
  #   static_configs:
  #   - targets: ['localhost:9090']
  # # Create a job for Docker daemons.
  # - job_name: 'docker'
  #   dockerswarm_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       role: nodes
  #   relabel_configs:
  #     # Fetch metrics on port 9323.
  #     - source_labels: [__meta_dockerswarm_node_address]
  #       target_label: __address__
  #       replacement: $1:9323
  #     # Set hostname as instance label
  #     - source_labels: [__meta_dockerswarm_node_hostname]
  #       target_label: instance

