# https://grafana.com/blog/2020/02/25/step-by-step-guide-to-setting-up-prometheus-alertmanager-with-slack-pagerduty-and-gmail/
# https://prometheus.io/docs/alerting/latest/configuration/
# https://prometheus.io/docs/alerting/latest/notification_examples/

# global:
#   pagerduty_url: "http://localhost"
#   opsgenie_api_url: "http://localhost"
#   wechat_api_url: "http://localhost"
#   victorops_api_url: "http://localhost"
#   slack_api_url: "http://localhost"

route:
  receiver: "default"
  group_interval: 5m
  group_wait: 30s
  repeat_interval: 12h
  group_by: ['...']
  # routes:
  #   - receiver: "demo-receiver"
  #     match_re:
  #       alertname: "demo-alert"
  #       env: "${ENV:-demo}"

receivers:
  - name: "default"
  # - name: "demo-receiver"
  #   webhook_configs:
  #   - url: "http://prom-msteams:2000/demo-alerts"
  #     send_resolved: true
