global:
  scrape_interval: 30s
  scrape_timeout: 30s
  evaluation_interval: 30s

rule_files:
  - /swarmetheus_data/rules/*.yml

alerting:
  alertmanagers:
    - file_sd_configs:
      - files:
        - /swarmetheus_data/alerting/*.yml

scrape_configs:
  - job_name: 'swarmetheus'
    file_sd_configs:
    - files:
      - /swarmetheus_data/files/*.yml
